services:
  adonis-app:
    build: .
    ports:
      - "3333:3333"
    environment:
      TZ: UTC
      PORT: 3333
      HOST: 0.0.0.0
      NODE_ENV: development
      DB_CONNECTION: pg
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_DATABASE: db_igmar
      DB_HOST: postgres      # <— nombre del servicio en la red
      DB_PORT: 5432
      MONGO_URL: mongodb://admin:admin123@mongo:27017/igmar_db?authSource=admin
    volumes:
      - ./:/app
    networks:
      - igmar-net

networks:
  igmar-net:
    external: true
