services:

  adonis-app:
    build: .
    ports:
      - "3333:3333"
    restart: unless-stopped
    environment:
      LOG_LEVEL: info
      APP_KEY: 7Otq2phcA_g__DtX_NQLJZRQN7jxIdFa
      TZ: UTC
      PORT: 3333
      HOST: 0.0.0.0
      NODE_ENV: development
      DB_CONNECTION: pg
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_DATABASE: db_igmar
      DB_HOST: postgres      
      DB_PORT: 5432
      MONGO_URL: mongodb://admin:admin123@mongo:5000,18.217.230.121:1006/igmar_db?authSource=admin&replicaSet=rs0
    volumes:
      - ./:/app
    networks:
      - igmar-net
      - frontend-net

networks:
  igmar-net:
    external: true

  frontend-net:
    external: true