name: Trabajar directo en el servidor

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: practicas

    steps:
      - name: Try SSH Deploy (Host 1)
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: ${{ secrets.SERVER_HOST_EXTERNAL }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd projects/server-battleship-igmar
            git pull origin master
            docker restart server-battleship-igmar-adonis-app-1

      - name: Try SSH Deploy (Host 2 if Host 1 failed)
        if: steps.previous-step-name.outcome == 'failure'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST_INTERNAL }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd projects/server-battleship-igmar
            git pull origin master
            docker restart server-battleship-igmar-adonis-app-1
